apiVersion: apps/v1
kind: Deployment
metadata:
  name: team-splitter-backend-deployment
  labels:
    app: team-splitter-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: team-splitter-backend
  template:
    metadata:
      labels:
        app: team-splitter-backend
    spec:
      containers:
        - name: team-splitter-backend
          image: ghcr.io/team-splitter/team-splitter-server:1.57
          ports:
            - containerPort: 8080
          env:
            - name: TEAM-SPLITTER_DB_POSTGRES_URL
              valueFrom:
                secretKeyRef:
                  name: crdb-secret
                  key: url
            - name: TEAM-SPLITTER_DB_POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: crdb-secret
                  key: user
            - name: TEAM-SPLITTER_DB_POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: crdb-secret
                  key: password
            - name: TELEGRAM_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: team-splitter-secret
                  key: telegram-bot-token
            - name: GAME_SCHEDULER_CHAT_ID
              value: "-1001517284618"
            - name: GAME_SCHEDULER_TASK_OPEN_POLL_CRON
              value: "0 * * * * *"
            - name: GAME_SCHEDULER_TASK_OPEN_POLL_LOOKFORWARDINDAYS
      imagePullSecrets:
        - name: regcred

---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
#  type: NodePort
  selector:
    app: team-splitter-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
#      nodePort: 30100