apiVersion: apps/v1
kind: Deployment
metadata:
  name: team-splitter-backend-deployment
  labels:
    app: team-splitter-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: team-splitter-backend
  template:
    metadata:
      labels:
        app: team-splitter-backend
    spec:
      containers:
        - name: team-splitter-backend
          image: ghcr.io/team-splitter/team-splitter-server:1.56
          ports:
            - containerPort: 8080
          env:
            - name: TEAM-SPLITTER_DB_POSTGRES_URL
              valueFrom:
                secretKeyRef:
                  name: crdb-secret
                  key: url
            - name: TEAM-SPLITTER_DB_POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: crdb-secret
                  key: user
            - name: TEAM-SPLITTER_DB_POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: crdb-secret
                  key: password
      imagePullSecrets:
        - name: regcred
      dnsPolicy: Default

---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
#  type: NodePort
  selector:
    app: team-splitter-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
#      nodePort: 30100