version: "3.8"

services:
  crdb:
    image: cockroachdb/cockroach:v19.2.2
    ports:
      - "26257:26257"
      - "8090:8080"
    command: start-single-node --insecure
    restart: unless-stopped
    volumes:
      - "crdb_volume:/cockroach/cockroach-data"
    networks:
      - team-splitter-net
  app:
    depends_on:
      - crdb
    build: ./team-splitter-app
    env_file: ./.env
    environment:
      SPRING_APPLICATION_JSON: '{
        "telegram.bot.token": "${TELEGRAM_BOT_TOKEN}",
        "team-splitter.db.postgres.url"  : "jdbc:postgresql://crdb:26257/defaultdb",
         "team-splitter.db.postgres.user" : "root",
         "team-splitter.db.postgres.password" : ""
      }'
    volumes:
      - .m2:/root/.m2
    networks:
      - team-splitter-net
    stdin_open: true
    tty: true

  backend:
    depends_on:
      - crdb
    build: ./team-splitter-server
    env_file: ./.env
    environment:
      SPRING_APPLICATION_JSON: '{
              "team-splitter.db.postgres.url"  : "jdbc:postgresql://crdb:26257/defaultdb",
               "team-splitter.db.postgres.user" : "root",
               "team-splitter.db.postgres.password" : ""
            }'
    networks:
      - team-splitter-net
    stdin_open: true
    ports:
      - "8080:8080"

volumes:
  crdb_volume:

networks:
  team-splitter-net: