db: "postgres"

team-splitter:
  db:
    postgres:
      url: ""
      user: ""
      password: ""

spring:
  liquibase:
    enabled: false
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: true
      WRITE_DATE_TIMESTAMPS_AS_NANOSECONDS: false
    deserialization:
      READ_DATE_TIMESTAMPS_AS_NANOSECONDS: false