telegram:
  bot:
    token: ""#Bot token

command:
  allowed-users: "355281005,156023871" #"Maksym"
#  allowed-users: ""
db: "postgres"

spring:
  liquibase:
    enabled: false

team-splitter:
  db:
    postgres:
      url: ""
      user: ""
      password: ""

game:
  scheduler:
    enabled: false
    chat_id: -1001517284618 # dev
    task:
      periodInSeconds: 10
      open_poll:
        enabled: false
        lookForwardInDays: 2
      close_poll:
        enabled: false
        lookForwardInHours: 2
      split_teams:
        enabled: false
        lookForwardInHours: 1