apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot-deployment
  labels:
    app: team-splitter-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: team-splitter-bot
  template:
    metadata:
      labels:
        app: team-splitter-bot
    spec:
      containers:
        - name: team-splitter-bot
          image: ghcr.io/team-splitter/team-splitter-bot:1.52
          env:
            - name: TEAM-SPLITTER_DB_MYSQL_URL
              value: jdbc:mysql://mysql-service:3306/team-splitter?allowPublicKeyRetrieval=true&useSSL=false
            - name: TEAM-SPLITTER_DB_MYSQL_USER
              value: root
            - name: TEAM-SPLITTER_DB_MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-password
            - name: TELEGRAM_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: team-splitter-secret
                  key: telegram-bot-token
            - name: GAME_SCHEDULER_ENABLED
              value: "true"
            - name: GAME_SCHEDULER_CHAT_ID
              value: "-1001333858606"
            - name: GAME_SCHEDULER_TASK_PERIODINSECONDS
              value: "300"
            - name: GAME_SCHEDULER_TASK_OPEN_POLL_ENABLED
              value: "true"
            - name: GAME_SCHEDULER_TASK_OPEN_POLL_LOOKFORWARDINDAYS
              value: "2"
            - name: GAME_SCHEDULER_TASK_CLOSE_POLL_ENABLED
              value: "false"
            - name: GAME_SCHEDULER_TASK_SPLIT_TEAMS_ENABLED
              value: "false"
      imagePullSecrets:
        - name: regcred
