apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/team-splitter/team-splitter-ui:0.1.42
          ports:
            - containerPort: 443
          env:
          - name: REACT_APP_ENV
            value: prod
          volumeMounts:
            - mountPath: "/etc/nginx/ssl"
              name: nginx-ssl
              readOnly: true
      volumes:
        - name: nginx-ssl
          secret:
            secretName: nginx-secret-cert
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
#  type: NodePort
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - name: http
      protocol: TCP
      port: 9000
      targetPort: 443
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
#      nodePort: 30200