name: Release and Cut Tag

on:
  workflow_dispatch:
  
permissions:
  contents: write
  packages: write

jobs:
  build:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
        server-id: github
    - name: Login GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Release version
      run: |
        release_version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout | cut -d- -f1)
        mvn versions:set -DnewVersion=${release_version}
        echo "Version is ${release_version}"
        
        mvn -B deploy -Pdocker-deploy -DskipTests
        
        mvn versions:revert
        
        git config user.email "actions@github.com"
        git config user.name "GitHub Actions"

        mvn -B -DskipTests -DscmCommentPrefix="[platform] " \
        -DscmDevelopmentCommitComment="@{prefix} prepare next development iteration [skip ci]" \
        -DscmReleaseCommitComment="@{prefix} prepare release @{releaseLabel} [skip ci]" \
        release:clean release:prepare
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
