name: DB Migration

on:
  workflow_dispatch:


jobs:
  run-db-migration:
    
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - uses: liquibase-github-actions/update@v4.26.0
        with:
          changelogFile: "team-splitter-persistence/src/main/resources/db/crdb/changelog-master.xml"
          url: "jdbc:postgresql://arid-heron-9902.5xj.cockroachlabs.cloud:26257/team_splitter"
          password: "b9VZQogioloG6qzd7VLyMQ"
          username: "ci_test"
