name: DB Migration

on:
  workflow_dispatch:


jobs:
  run-db-migration:
    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
          server-id: github
      - name: Liquibase migration
        run: |
          mvn clean package
          mvn -f team-splitter-persistence liquibase:update -DDB_URL=jdbc:postgresql://arid-heron-9902.5xj.cockroachlabs.cloud:26257/team_splitter -DDB_USERNAME=ci_test -DDB_PASSWORD=b9VZQogioloG6qzd7VLyMQ
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
