name: DB Migration

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: "Select Environment"

jobs:
  run-db-migration:
    environment: ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
          server-id: github
      - name: Liquibase migration
        run: |
           mvn -f team-splitter-persistence clean compile liquibase:update
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DB_URL: ${{ secrets.CRDB_URL }}
          DB_USERNAME: ${{ secrets.CRDB_USERNAME }}
          DB_PASSWORD: ${{ secrets.CRDB_PASSWORD }}
